<?php return array(
  'daily' =>
    array(
      'weather_code' => 'Weather Code',
      'temperature_2m_max' => 'Maximum Temperature (2 m)',
      'temperature_2m_min' => 'Minimum Temperature (2 m)',
      'temperature_2m_mean' => 'Mean Temperature (2 m)',
      'apparent_temperature_max' => 'Maximum Apparent Temperature (2 m)',
      'apparent_temperature_min' => 'Minimum Apparent Temperature (2 m)',
      'apparent_temperature_mean' => 'Mean Apparent Temperature (2m)',
      'sunrise' => 'Sunrise',
      'sunset' => 'Sunset',
      'daylight_duration' => 'Daylight Duration',
      'sunshine_duration' => 'Sunshine Duration',
      'precipitation_sum' => 'Precipitation Sum',
      'rain_sum' => 'Rain Sum',
      'snowfall_sum' => 'Snowfall Sum',
      'precipitation_hours' => 'Precipitation Hours',
      'wind_speed_10m_max' => 'Maximum Wind Speed (10 m)',
      'wind_gust_10m_max' => 'Maximum Wind Gust (10 m)',
      'wind_direction_10m_dominant' => 'Dominant Wind Direction (10 m)',
      'shortwave_radiation_sum' => 'Shortwave Radiation Sum',
      'et0_fao_evapotranspiration' => 'Reference Evapotranspiration(ET₀)',
      'heat_index' => 'Heat Index',
      'heat_index2' => 'Heat Index2',
      'heat_index3' => 'Heat Index3',
    ),
);